//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlbum
    {
        public tblAlbum()
        {
            this.tblTracks = new HashSet<tblTrack>();
        }
         
        public int Albm_id { get; set; }
        public Nullable<int> Aritist_id { get; set; }
        public string Albm_Name { get; set; }
        public Nullable<System.DateTime> RelaeseDate { get; set; }
        public byte[] picture { get; set; }
    
        public virtual tblArtist tblArtist { get; set; }
        public virtual ICollection<tblTrack> tblTracks { get; set; }
    }
}
