//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGenre
    {
        public tblGenre()
        {
            this.tblTracks = new HashSet<tblTrack>();
        }
    
        public int Gnre_id { get; set; }
        public string Gnre_Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tblTrack> tblTracks { get; set; }
    }
}
