//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrack
    {
        public int Trk_id { get; set; }
        public string Trk_name { get; set; }
        public Nullable<int> albm_id { get; set; }
        public Nullable<int> Gnre_id { get; set; }
    
        public virtual tblAlbum tblAlbum { get; set; }
        public virtual tblGenre tblGenre { get; set; }
    }
}
